postgres:
  image: postgres:9.5
  environment:
    POSTGRES_USER: abel 
    POSTGRES_PASSWORD: 'abel'
  ports:
    - '5432:5432'
  volumes:
    - abel-postgres:/var/lib/postgresql/data
redis:
  image: redis:3.2
  ports:
    - "6379:6379"
